apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsky-rss
  labels:
    app.kubernetes.io/name: bsky-rss
spec:
  resources:
    requests:
      storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
